
trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
- group: DetaVariableGroup
- group:  BuildVariablesGroup

steps:

- task: GoTool@0
  displayName: Use Go 1.10
- task: Go@0
  displayName: go get
  inputs:
    arguments: -d
- task: Go@0
  displayName: go build
  inputs:
    command: build
    arguments: -o "GoSecretsdump.exe"
    
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PowerShell@2
  displayName: 'Move File to Deta'
  inputs:
    targetType: 'inline'
    script: |
      $Files = (Get-ChildItem -Filter *.exe -Path $(build.artifactstagingdirectory) -Recurse).FullName
      $Date = Get-Date -Format ddMMyyyy
      $FolderName = $Date
      $jsonBase = @{}   
        
      $UploadHeaders = @{
          "X-API-Key" = $env:UploadHeadersAPI
      }

      foreach ($NewName in $Files)
      {
        echo $NewName
        $UploadURL = "https://drive.deta.sh/v1/$env:UploadProjectKey/Uploads/files?name=$("/"+$FolderName+"/"+$($NewName.split('\')[7]))"
        Invoke-WebRequest -Uri $UploadURL -Headers $UploadHeaders -Infile $NewName -Method POST
      }
  env:
    UploadHeadersAPI: $(UploadHeadersAPI)
    UploadProjectKey: $(UploadProjectKey)