  
name: Test
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - uses: actions/checkout@v1
        with:
          repository: c-sto/ntds_reference
          ref: master
          path: ./src/github.com/${{ github.repository }}/test/
      - name: Vet on windows
        run: GOOS=windows go vet
      - name: Vet on darwin
        run: GOOS=darwin go vet
      - name: Vet on linux
        run: GOOS=linux go vet
      - name: Run tests
        run: go test ./...
